---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cluster-api-provider-ionoscloud
    app.kubernetes.io/part-of: cluster-api-provider-ionoscloud
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cluster-api-provider-ionoscloud
    app.kubernetes.io/part-of: cluster-api-provider-ionoscloud
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - "--leader-elect"
        image: controller:latest
        name: manager
        ports:
        - containerPort: 8443
          name: diagnostics
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          privileged: false
          runAsUser: 65532
          runAsGroup: 65532
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  namespace: system
  name: controller-manager-diagnostics-service
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: diagnostics-service
    app.kubernetes.io/instance: controller-manager-diagnostics-service
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: cluster-api-provider-ionoscloud
    app.kubernetes.io/part-of: cluster-api-provider-ionoscloud
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
  ports:
  - name: diagnostics-svc
    protocol: TCP
    port: 8443
    targetPort: diagnostics
