/*
Copyright 2024 IONOS Cloud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by mockery v2.36.0. DO NOT EDIT.

package client_test

import (
	context "context"

	ionoscloud "github.com/ionos-cloud/sdk-go/v6"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AttachToLAN provides a mock function with given fields: ctx, datacenterID, lanID, nic
func (_m *MockClient) AttachToLAN(ctx context.Context, datacenterID string, lanID string, nic ionoscloud.Nic) (*ionoscloud.Nic, error) {
	ret := _m.Called(ctx, datacenterID, lanID, nic)

	var r0 *ionoscloud.Nic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ionoscloud.Nic) (*ionoscloud.Nic, error)); ok {
		return rf(ctx, datacenterID, lanID, nic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ionoscloud.Nic) *ionoscloud.Nic); ok {
		r0 = rf(ctx, datacenterID, lanID, nic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Nic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ionoscloud.Nic) error); ok {
		r1 = rf(ctx, datacenterID, lanID, nic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_AttachToLAN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToLAN'
type MockClient_AttachToLAN_Call struct {
	*mock.Call
}

// AttachToLAN is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - lanID string
//   - nic ionoscloud.Nic
func (_e *MockClient_Expecter) AttachToLAN(ctx interface{}, datacenterID interface{}, lanID interface{}, nic interface{}) *MockClient_AttachToLAN_Call {
	return &MockClient_AttachToLAN_Call{Call: _e.mock.On("AttachToLAN", ctx, datacenterID, lanID, nic)}
}

func (_c *MockClient_AttachToLAN_Call) Run(run func(ctx context.Context, datacenterID string, lanID string, nic ionoscloud.Nic)) *MockClient_AttachToLAN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(ionoscloud.Nic))
	})
	return _c
}

func (_c *MockClient_AttachToLAN_Call) Return(_a0 *ionoscloud.Nic, _a1 error) *MockClient_AttachToLAN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_AttachToLAN_Call) RunAndReturn(run func(context.Context, string, string, ionoscloud.Nic) (*ionoscloud.Nic, error)) *MockClient_AttachToLAN_Call {
	_c.Call.Return(run)
	return _c
}

// CheckRequestStatus provides a mock function with given fields: ctx, requestID
func (_m *MockClient) CheckRequestStatus(ctx context.Context, requestID string) (*ionoscloud.RequestStatus, error) {
	ret := _m.Called(ctx, requestID)

	var r0 *ionoscloud.RequestStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ionoscloud.RequestStatus, error)); ok {
		return rf(ctx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ionoscloud.RequestStatus); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.RequestStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CheckRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRequestStatus'
type MockClient_CheckRequestStatus_Call struct {
	*mock.Call
}

// CheckRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
func (_e *MockClient_Expecter) CheckRequestStatus(ctx interface{}, requestID interface{}) *MockClient_CheckRequestStatus_Call {
	return &MockClient_CheckRequestStatus_Call{Call: _e.mock.On("CheckRequestStatus", ctx, requestID)}
}

func (_c *MockClient_CheckRequestStatus_Call) Run(run func(ctx context.Context, requestID string)) *MockClient_CheckRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_CheckRequestStatus_Call) Return(_a0 *ionoscloud.RequestStatus, _a1 error) *MockClient_CheckRequestStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CheckRequestStatus_Call) RunAndReturn(run func(context.Context, string) (*ionoscloud.RequestStatus, error)) *MockClient_CheckRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLAN provides a mock function with given fields: ctx, datacenterID, properties
func (_m *MockClient) CreateLAN(ctx context.Context, datacenterID string, properties ionoscloud.LanPropertiesPost) (string, error) {
	ret := _m.Called(ctx, datacenterID, properties)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ionoscloud.LanPropertiesPost) (string, error)); ok {
		return rf(ctx, datacenterID, properties)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ionoscloud.LanPropertiesPost) string); ok {
		r0 = rf(ctx, datacenterID, properties)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ionoscloud.LanPropertiesPost) error); ok {
		r1 = rf(ctx, datacenterID, properties)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateLAN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLAN'
type MockClient_CreateLAN_Call struct {
	*mock.Call
}

// CreateLAN is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - properties ionoscloud.LanPropertiesPost
func (_e *MockClient_Expecter) CreateLAN(ctx interface{}, datacenterID interface{}, properties interface{}) *MockClient_CreateLAN_Call {
	return &MockClient_CreateLAN_Call{Call: _e.mock.On("CreateLAN", ctx, datacenterID, properties)}
}

func (_c *MockClient_CreateLAN_Call) Run(run func(ctx context.Context, datacenterID string, properties ionoscloud.LanPropertiesPost)) *MockClient_CreateLAN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ionoscloud.LanPropertiesPost))
	})
	return _c
}

func (_c *MockClient_CreateLAN_Call) Return(_a0 string, _a1 error) *MockClient_CreateLAN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateLAN_Call) RunAndReturn(run func(context.Context, string, ionoscloud.LanPropertiesPost) (string, error)) *MockClient_CreateLAN_Call {
	_c.Call.Return(run)
	return _c
}

// CreateServer provides a mock function with given fields: ctx, datacenterID, properties, entities
func (_m *MockClient) CreateServer(ctx context.Context, datacenterID string, properties ionoscloud.ServerProperties, entities ionoscloud.ServerEntities) (*ionoscloud.Server, string, error) {
	ret := _m.Called(ctx, datacenterID, properties, entities)

	var r0 *ionoscloud.Server
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ionoscloud.ServerProperties, ionoscloud.ServerEntities) (*ionoscloud.Server, string, error)); ok {
		return rf(ctx, datacenterID, properties, entities)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ionoscloud.ServerProperties, ionoscloud.ServerEntities) *ionoscloud.Server); ok {
		r0 = rf(ctx, datacenterID, properties, entities)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ionoscloud.ServerProperties, ionoscloud.ServerEntities) string); ok {
		r1 = rf(ctx, datacenterID, properties, entities)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, ionoscloud.ServerProperties, ionoscloud.ServerEntities) error); ok {
		r2 = rf(ctx, datacenterID, properties, entities)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClient_CreateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServer'
type MockClient_CreateServer_Call struct {
	*mock.Call
}

// CreateServer is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - properties ionoscloud.ServerProperties
//   - entities ionoscloud.ServerEntities
func (_e *MockClient_Expecter) CreateServer(ctx interface{}, datacenterID interface{}, properties interface{}, entities interface{}) *MockClient_CreateServer_Call {
	return &MockClient_CreateServer_Call{Call: _e.mock.On("CreateServer", ctx, datacenterID, properties, entities)}
}

func (_c *MockClient_CreateServer_Call) Run(run func(ctx context.Context, datacenterID string, properties ionoscloud.ServerProperties, entities ionoscloud.ServerEntities)) *MockClient_CreateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ionoscloud.ServerProperties), args[3].(ionoscloud.ServerEntities))
	})
	return _c
}

func (_c *MockClient_CreateServer_Call) Return(_a0 *ionoscloud.Server, _a1 string, _a2 error) *MockClient_CreateServer_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockClient_CreateServer_Call) RunAndReturn(run func(context.Context, string, ionoscloud.ServerProperties, ionoscloud.ServerEntities) (*ionoscloud.Server, string, error)) *MockClient_CreateServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLAN provides a mock function with given fields: ctx, datacenterID, lanID
func (_m *MockClient) DeleteLAN(ctx context.Context, datacenterID string, lanID string) (string, error) {
	ret := _m.Called(ctx, datacenterID, lanID)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, datacenterID, lanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, datacenterID, lanID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, datacenterID, lanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_DeleteLAN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLAN'
type MockClient_DeleteLAN_Call struct {
	*mock.Call
}

// DeleteLAN is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - lanID string
func (_e *MockClient_Expecter) DeleteLAN(ctx interface{}, datacenterID interface{}, lanID interface{}) *MockClient_DeleteLAN_Call {
	return &MockClient_DeleteLAN_Call{Call: _e.mock.On("DeleteLAN", ctx, datacenterID, lanID)}
}

func (_c *MockClient_DeleteLAN_Call) Run(run func(ctx context.Context, datacenterID string, lanID string)) *MockClient_DeleteLAN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteLAN_Call) Return(_a0 string, _a1 error) *MockClient_DeleteLAN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_DeleteLAN_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockClient_DeleteLAN_Call {
	_c.Call.Return(run)
	return _c
}

// DestroyServer provides a mock function with given fields: ctx, datacenterID, serverID
func (_m *MockClient) DestroyServer(ctx context.Context, datacenterID string, serverID string) error {
	ret := _m.Called(ctx, datacenterID, serverID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, datacenterID, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DestroyServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyServer'
type MockClient_DestroyServer_Call struct {
	*mock.Call
}

// DestroyServer is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - serverID string
func (_e *MockClient_Expecter) DestroyServer(ctx interface{}, datacenterID interface{}, serverID interface{}) *MockClient_DestroyServer_Call {
	return &MockClient_DestroyServer_Call{Call: _e.mock.On("DestroyServer", ctx, datacenterID, serverID)}
}

func (_c *MockClient_DestroyServer_Call) Run(run func(ctx context.Context, datacenterID string, serverID string)) *MockClient_DestroyServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DestroyServer_Call) Return(_a0 error) *MockClient_DestroyServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DestroyServer_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DestroyServer_Call {
	_c.Call.Return(run)
	return _c
}

// DestroyVolume provides a mock function with given fields: ctx, datacenterID, volumeID
func (_m *MockClient) DestroyVolume(ctx context.Context, datacenterID string, volumeID string) error {
	ret := _m.Called(ctx, datacenterID, volumeID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, datacenterID, volumeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DestroyVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DestroyVolume'
type MockClient_DestroyVolume_Call struct {
	*mock.Call
}

// DestroyVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - volumeID string
func (_e *MockClient_Expecter) DestroyVolume(ctx interface{}, datacenterID interface{}, volumeID interface{}) *MockClient_DestroyVolume_Call {
	return &MockClient_DestroyVolume_Call{Call: _e.mock.On("DestroyVolume", ctx, datacenterID, volumeID)}
}

func (_c *MockClient_DestroyVolume_Call) Run(run func(ctx context.Context, datacenterID string, volumeID string)) *MockClient_DestroyVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DestroyVolume_Call) Return(_a0 error) *MockClient_DestroyVolume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DestroyVolume_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DestroyVolume_Call {
	_c.Call.Return(run)
	return _c
}

// GetLAN provides a mock function with given fields: ctx, datacenterID, lanID
func (_m *MockClient) GetLAN(ctx context.Context, datacenterID string, lanID string) (*ionoscloud.Lan, error) {
	ret := _m.Called(ctx, datacenterID, lanID)

	var r0 *ionoscloud.Lan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ionoscloud.Lan, error)); ok {
		return rf(ctx, datacenterID, lanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ionoscloud.Lan); ok {
		r0 = rf(ctx, datacenterID, lanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Lan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, datacenterID, lanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetLAN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLAN'
type MockClient_GetLAN_Call struct {
	*mock.Call
}

// GetLAN is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - lanID string
func (_e *MockClient_Expecter) GetLAN(ctx interface{}, datacenterID interface{}, lanID interface{}) *MockClient_GetLAN_Call {
	return &MockClient_GetLAN_Call{Call: _e.mock.On("GetLAN", ctx, datacenterID, lanID)}
}

func (_c *MockClient_GetLAN_Call) Run(run func(ctx context.Context, datacenterID string, lanID string)) *MockClient_GetLAN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetLAN_Call) Return(_a0 *ionoscloud.Lan, _a1 error) *MockClient_GetLAN_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetLAN_Call) RunAndReturn(run func(context.Context, string, string) (*ionoscloud.Lan, error)) *MockClient_GetLAN_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequests provides a mock function with given fields: ctx, method, path
func (_m *MockClient) GetRequests(ctx context.Context, method string, path string) ([]ionoscloud.Request, error) {
	ret := _m.Called(ctx, method, path)

	var r0 []ionoscloud.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]ionoscloud.Request, error)); ok {
		return rf(ctx, method, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []ionoscloud.Request); ok {
		r0 = rf(ctx, method, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ionoscloud.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, method, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequests'
type MockClient_GetRequests_Call struct {
	*mock.Call
}

// GetRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - method string
//   - path string
func (_e *MockClient_Expecter) GetRequests(ctx interface{}, method interface{}, path interface{}) *MockClient_GetRequests_Call {
	return &MockClient_GetRequests_Call{Call: _e.mock.On("GetRequests", ctx, method, path)}
}

func (_c *MockClient_GetRequests_Call) Run(run func(ctx context.Context, method string, path string)) *MockClient_GetRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetRequests_Call) Return(_a0 []ionoscloud.Request, _a1 error) *MockClient_GetRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetRequests_Call) RunAndReturn(run func(context.Context, string, string) ([]ionoscloud.Request, error)) *MockClient_GetRequests_Call {
	_c.Call.Return(run)
	return _c
}

// GetServer provides a mock function with given fields: ctx, datacenterID, serverID
func (_m *MockClient) GetServer(ctx context.Context, datacenterID string, serverID string) (*ionoscloud.Server, error) {
	ret := _m.Called(ctx, datacenterID, serverID)

	var r0 *ionoscloud.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ionoscloud.Server, error)); ok {
		return rf(ctx, datacenterID, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ionoscloud.Server); ok {
		r0 = rf(ctx, datacenterID, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, datacenterID, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServer'
type MockClient_GetServer_Call struct {
	*mock.Call
}

// GetServer is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - serverID string
func (_e *MockClient_Expecter) GetServer(ctx interface{}, datacenterID interface{}, serverID interface{}) *MockClient_GetServer_Call {
	return &MockClient_GetServer_Call{Call: _e.mock.On("GetServer", ctx, datacenterID, serverID)}
}

func (_c *MockClient_GetServer_Call) Run(run func(ctx context.Context, datacenterID string, serverID string)) *MockClient_GetServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetServer_Call) Return(_a0 *ionoscloud.Server, _a1 error) *MockClient_GetServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetServer_Call) RunAndReturn(run func(context.Context, string, string) (*ionoscloud.Server, error)) *MockClient_GetServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolume provides a mock function with given fields: ctx, datacenterID, volumeID
func (_m *MockClient) GetVolume(ctx context.Context, datacenterID string, volumeID string) (*ionoscloud.Volume, error) {
	ret := _m.Called(ctx, datacenterID, volumeID)

	var r0 *ionoscloud.Volume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ionoscloud.Volume, error)); ok {
		return rf(ctx, datacenterID, volumeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ionoscloud.Volume); ok {
		r0 = rf(ctx, datacenterID, volumeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Volume)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, datacenterID, volumeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetVolume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolume'
type MockClient_GetVolume_Call struct {
	*mock.Call
}

// GetVolume is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
//   - volumeID string
func (_e *MockClient_Expecter) GetVolume(ctx interface{}, datacenterID interface{}, volumeID interface{}) *MockClient_GetVolume_Call {
	return &MockClient_GetVolume_Call{Call: _e.mock.On("GetVolume", ctx, datacenterID, volumeID)}
}

func (_c *MockClient_GetVolume_Call) Run(run func(ctx context.Context, datacenterID string, volumeID string)) *MockClient_GetVolume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetVolume_Call) Return(_a0 *ionoscloud.Volume, _a1 error) *MockClient_GetVolume_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetVolume_Call) RunAndReturn(run func(context.Context, string, string) (*ionoscloud.Volume, error)) *MockClient_GetVolume_Call {
	_c.Call.Return(run)
	return _c
}

// ListLANs provides a mock function with given fields: ctx, datacenterID
func (_m *MockClient) ListLANs(ctx context.Context, datacenterID string) (*ionoscloud.Lans, error) {
	ret := _m.Called(ctx, datacenterID)

	var r0 *ionoscloud.Lans
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ionoscloud.Lans, error)); ok {
		return rf(ctx, datacenterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ionoscloud.Lans); ok {
		r0 = rf(ctx, datacenterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Lans)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, datacenterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListLANs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLANs'
type MockClient_ListLANs_Call struct {
	*mock.Call
}

// ListLANs is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
func (_e *MockClient_Expecter) ListLANs(ctx interface{}, datacenterID interface{}) *MockClient_ListLANs_Call {
	return &MockClient_ListLANs_Call{Call: _e.mock.On("ListLANs", ctx, datacenterID)}
}

func (_c *MockClient_ListLANs_Call) Run(run func(ctx context.Context, datacenterID string)) *MockClient_ListLANs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ListLANs_Call) Return(_a0 *ionoscloud.Lans, _a1 error) *MockClient_ListLANs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListLANs_Call) RunAndReturn(run func(context.Context, string) (*ionoscloud.Lans, error)) *MockClient_ListLANs_Call {
	_c.Call.Return(run)
	return _c
}

// ListServers provides a mock function with given fields: ctx, datacenterID
func (_m *MockClient) ListServers(ctx context.Context, datacenterID string) (*ionoscloud.Servers, error) {
	ret := _m.Called(ctx, datacenterID)

	var r0 *ionoscloud.Servers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ionoscloud.Servers, error)); ok {
		return rf(ctx, datacenterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ionoscloud.Servers); ok {
		r0 = rf(ctx, datacenterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Servers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, datacenterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServers'
type MockClient_ListServers_Call struct {
	*mock.Call
}

// ListServers is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
func (_e *MockClient_Expecter) ListServers(ctx interface{}, datacenterID interface{}) *MockClient_ListServers_Call {
	return &MockClient_ListServers_Call{Call: _e.mock.On("ListServers", ctx, datacenterID)}
}

func (_c *MockClient_ListServers_Call) Run(run func(ctx context.Context, datacenterID string)) *MockClient_ListServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ListServers_Call) Return(_a0 *ionoscloud.Servers, _a1 error) *MockClient_ListServers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListServers_Call) RunAndReturn(run func(context.Context, string) (*ionoscloud.Servers, error)) *MockClient_ListServers_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function with given fields: ctx, datacenterID
func (_m *MockClient) ListVolumes(ctx context.Context, datacenterID string) (*ionoscloud.Volumes, error) {
	ret := _m.Called(ctx, datacenterID)

	var r0 *ionoscloud.Volumes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ionoscloud.Volumes, error)); ok {
		return rf(ctx, datacenterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ionoscloud.Volumes); ok {
		r0 = rf(ctx, datacenterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ionoscloud.Volumes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, datacenterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockClient_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - ctx context.Context
//   - datacenterID string
func (_e *MockClient_Expecter) ListVolumes(ctx interface{}, datacenterID interface{}) *MockClient_ListVolumes_Call {
	return &MockClient_ListVolumes_Call{Call: _e.mock.On("ListVolumes", ctx, datacenterID)}
}

func (_c *MockClient_ListVolumes_Call) Run(run func(ctx context.Context, datacenterID string)) *MockClient_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ListVolumes_Call) Return(_a0 *ionoscloud.Volumes, _a1 error) *MockClient_ListVolumes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListVolumes_Call) RunAndReturn(run func(context.Context, string) (*ionoscloud.Volumes, error)) *MockClient_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForRequest provides a mock function with given fields: ctx, requestURL
func (_m *MockClient) WaitForRequest(ctx context.Context, requestURL string) error {
	ret := _m.Called(ctx, requestURL)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, requestURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_WaitForRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForRequest'
type MockClient_WaitForRequest_Call struct {
	*mock.Call
}

// WaitForRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestURL string
func (_e *MockClient_Expecter) WaitForRequest(ctx interface{}, requestURL interface{}) *MockClient_WaitForRequest_Call {
	return &MockClient_WaitForRequest_Call{Call: _e.mock.On("WaitForRequest", ctx, requestURL)}
}

func (_c *MockClient_WaitForRequest_Call) Run(run func(ctx context.Context, requestURL string)) *MockClient_WaitForRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_WaitForRequest_Call) Return(_a0 error) *MockClient_WaitForRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_WaitForRequest_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_WaitForRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
