name: End to End Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  e2e:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install kubectl and kustomize
        run: |
          snap install kubectl --classic
          snap install kustomize

      - name: Set up dependencies
        run: make deps

      - name: Run e2e tests
        run: make GINKGO_LABEL="!Conformance" test-e2e

      - name: Redact sensitive data
        if: always()
        run: ./hack/scripts/remove-sensitive-data-from-artifacts.sh

      - name : Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: _artifacts
